package de.monticore.coevolution;
import target/man-test/de/monticore/Address.java


public class AdressHC {
    /* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/
    String city;

    /* generated by template cd2java.Attribute*/
    String street;

    /* generated by template cd2java.Attribute*/
     public int number;

    public int neighbor(int number){
      return number +1;
    }


    public int neighbor(){
      int number = 0;
      return number + 1;
    }
}
