# (c) https://github.com/MontiCore/monticore

image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
  key: ${CI_COMMIT_REF_SLUG}
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy
  - trigger
  - check
  - mirror

build:
  stage: build
  script:
  - "gradle assemble --refresh-dependencies $GRADLE_OPT $ARGS1"
  artifacts:
    paths:
    - "."
    expire_in: 1 week

test:
  stage: test
  dependencies:
    - build
  script:
  - "gradle check $GRADLE_OPT $ARGS2"

trigger-langexp:
  stage: trigger
  trigger:
    project: monticore/langexperiments
    branch: dev
  only:
    - develop

deploy:
  stage: deploy
  only:
    - develop
  dependencies:
    - build
  script:
    - "gradle publish $GRADLE_OPT $ARGS3 -PmavenPassword=$password -PmavenUser=$username"
  
checkMDLinks:
  stage: check
  allow_failure: true
  dependencies:
    - deploy
  script:
    - "curl --location --header \"PRIVATE-TOKEN: $secibuildtoken\" \"https://git.rwth-aachen.de/api/v4/projects/monticore%2Fauxiliary-development-tools%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkCheckerCLI.jar?job=build\" --output MDLinkCheckerCLI.jar"
    - "url=https://git.rwth-aachen.de/monticore/cd4analysis/cd4analysis/-/tree/develop"
    - "linkCheckRes=$(java -jar MDLinkCheckerCLI.jar -url $url -t $secibuildtoken -p)"
    - "echo \"$linkCheckRes\""
    - "if [[ $linkCheckRes == *\"ERROR\"* ]]; then exit 1; fi"
  only:
    - develop

githubmirror:
  stage: mirror
  dependencies:
    - checkMDLinks
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SE_CIBUILD_SSH_PRIV_KEY")
    - echo "$SE_CIBUILD_SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
    - git config --global user.email "noreply-ci@se-rwth.de"
    - git config --global user.name "MontiCore Mirroring Bot"
    - mkdir -p ~/.ssh
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script:
    - "curl --location --header \"PRIVATE-TOKEN: $secibuildtoken\" \"https://git.rwth-aachen.de/api/v4/projects/monticore%2Fauxiliary-development-tools%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkChangerCLI.jar?job=build\" --output MDLinkChangerCLI.jar"
    - sh pre/mirror.sh
    - cd ..
    - "if [ -d \"tmp\" ]; then rm -rf tmp; fi"
    - mkdir "tmp"
    - cd tmp
    - git clone git@github.com:MontiCore/cd4analysis.git
    - cd ..
    - rm -r tmp/cd4analysis/*
    - shopt -s extglob
    - mv cd4analysis/!(MDLinkChangerCLI.jar) tmp/cd4analysis/
    - cd tmp/cd4analysis
    - git add --all
    - "(git commit -m 'Updated branch with most recent version.') || true"
    - git push --force
    - cd ..
    - cd ..
    - rm -rf tmp
    - exit 0
  only:
    - develop


