mavenUser=${username}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
version=7.9.0-SNAPSHOT
mc_version=7.9.0-SNAPSHOT
commons_version=7.9.0-SNAPSHOT
shadow_plugin_version=7.1.2
useLocalRepo=false
org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true

buildVscodePlugin=false
buildIntelliJPlugin=false

publishMain=false
genTR=false
genTagging=false
