@startuml
  package "de.monticore.cd4code.parser" <<Frame>> {
    class Person implements entity.CorporateEntity {
      String name
      int age
      Date birthday
      List<String> nickNames
      +Person(String name)
      Set<Person> getParents()
    }
    class Grades
    class PhoneNumber
    class Address
  }

  package "entity" <<Frame>> {
    interface CorporateEntity
     {
      int vatNumber
    }
  }

  package "uni" <<Frame>> {
    class Student extends Person {
      StudentStatus status
      +change(StudentStatus status)
      void addFriends(Person... friends)
    }
    enum StudentStatus
     {
      BLUB
      Bala
      StudentStatus()

    }
  }

@enduml

