@startuml
<style>
	classDiagram {
		class {
			BackgroundColor White
			RoundCorner 0
	  }
	  legend {
      BackgroundColor White
      RoundCorner 0
    }
</style>
hide circle
hide empty members
  skinparam classAttributeIconSize 0
legend top right
  CD
end legend
class A {
  {field} int a
}
class B {
  {field} int b
}
class C {
  {field} int c
}
class D {
  {field} int a
  {field} int b
  {field} int c
}
center footer generated with MontiCore using PlantUML
@enduml
