/* (c) https://github.com/MontiCore/monticore */
plugins {
  id "jacoco"
  id "maven-publish"
}


dependencies {
  api "de.se_rwth.commons:se-commons-logging:$mc_version"

  implementation "de.se_rwth.commons:se-commons-utilities:$mc_version"
  implementation "org.apache.commons:commons-text:$commons_text_version"
  implementation "de.monticore:monticore-runtime:$mc_version"
  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
  testImplementation "org.junit.vintage:junit-vintage-engine:$junit_version"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_version"
}

description = 'CD: Runtime'

java {

}

publishing {
  publications {
    maven(MavenPublication) {
      groupId = 'de.monticore.lang'
      from components.java
    }
  }
  repositories.maven {
    credentials.username mavenUser
    credentials.password mavenPassword
    def releasesRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/"
    def snapshotsRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/"
    url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
  }
}

