import de.mclsg.TaskTypes

plugins {
  id 'java'
  id 'de.monticore.language-server' version "$mc_version"
  id 'maven-publish'
}

group 'de.monticore.lang'
version mc_version

sourceCompatibility = JavaVersion.VERSION_11

repositories {
  mavenCentral()
  maven {
    credentials.username mavenUser
    credentials.password mavenPassword
    url repo
  }
}

configurations {
  grammar { // require the "grammar" configuration to resolve "monticore-grammar-api" usages
    attributes {
      it.attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.class, "monticore-grammar-api"))
      // Note: This should not be necessary, but due to cd4as gradle setup we have to actually select
      it.attribute(Attribute.of('monticore.generator.sourceset', String), "main")
    }
  }
}

dependencies {
  // Language and parent language
  grammar project(":cdlang")
  grammar "de.monticore:monticore-grammar:$mc_version"
  implementation project(":cdlang")

  // Dependencies of cd4analysis, all marked as runtime in pom => we need to specify them here
  implementation "com.google.code.findbugs:jsr305:$findbugs_version"
  implementation "de.monticore:monticore-grammar:$mc_version"
  implementation "de.se_rwth.commons:se-commons-logging:$commons_version"
  implementation "de.se_rwth.commons:se-commons-utilities:$commons_version"
  implementation "com.google.guava:guava:$guava_version"
  implementation "net.sourceforge.plantuml:plantuml:1.2020.15"
  implementation "ch.qos.logback:logback-classic:$logback_version"
  implementation "commons-cli:commons-cli:$commons_cli_version"
  implementation "org.apache.commons:commons-lang3:$commons_lang_version"

  // MCLSG
  implementation "de.monticore.language-server:monticore-language-server-runtime:$mc_version"

  // Testing
  // JUnit Jupiter (JUnit 5) dependencies
  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
  testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_version"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_platform_version"
  testImplementation "ch.qos.logback:logback-classic:$logback_version"
}

test {
  useJUnitPlatform()
}

task autoconfigure(type: de.mclsg.task.AutoconfigureTask) {
  mclsg {
    languageName = "de.monticore.CD4Analysis"
    fileExtension = "cd"
  }
  if(("true").equals(getProperty('buildVscodePlugin'))){
    including(TaskTypes.VSCODE_PLUGIN)
  }
}
compileJava.dependsOn autoconfigure

tasks.generateCD4AnalysisLanguageServer.dependsOn(project(":cdlang").tasks.grammarsJar)
tasks.generateCD4AnalysisLanguageServer.dependsOn(project(":cdlang").tasks.grammarsForVariantJar)
tasks.packCD4AnalysisLanguageServer.dependsOn(project(":cdlang").tasks.jar)
