@startuml
<style>
	classDiagram {
		class {
			BackgroundColor White
			RoundCorner 0
	  }
	  legend {
      BackgroundColor White
      RoundCorner 0
    }
</style>
hide circle
hide empty members
  skinparam classAttributeIconSize 0
legend top right
  CD
end legend
namespace someOtherPackage {
  class A
  class B
}
class C
center footer generated with MontiCore using PlantUML
@enduml
