/* (c) https://github.com/MontiCore/monticore */
package de.monticore.refmodel;

import com.google.common.base.Preconditions;
import de.monticore.symboltable.ISymbol;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.function.Function;

/**
 * Represents a consistent set of bindings for a specific symbol kind. {@link T}<br>
 * <br>
 * <b>NOTE:</b> This is a helper class for INTERNAL IMPLEMENTATION of the language specific
 * interfaces
 * which provide access to bindings.
 * This class is mutable and should not be exposed to handwritten code! Instead, there are specific
 * mutation methods in the language specific interfaces.
 * For read-only access Set<Binding> should be used.
 *
 * @param <T> the kind of symbol for which bindings are defined.
 */
public class Bindings<T extends ISymbol> {
  
  /**
   * The map of bindings, where the key is computed from the reference element of the binding.
   * The key is computed using the {@link #computeKeyFunction}.
   */
  private final Map<String, Binding<T>> bindings = new HashMap<>();
  
  // TODO Do we need this on this level, or only for the context symbols one level higher?
  /*
   * This is a workaround so we do not have to deal with multiple instances of the same symbol
   * existing at runtime. e.g. there may be a VariableSymbol loaded by OCLMill with name "foo.Bar" and
   * a FieldSymbol with the same name loaded by CD4CMill which refer to exactly the same symbol
   * "foo.Bar" but are not equal as the Symbol classes generated by MontiCore do not implement
   * proper equals/hashCode methods.
   */
  /**
   * Function to compute the key for a binding based on its reference element.
   * This is used to ensure that bindings can be uniquely identified in the map.
   */
  private final Function<ISymbol, String> computeKeyFunction;
  
  public Bindings(Function<ISymbol, String> computeKeyFunction) {
    this.computeKeyFunction = computeKeyFunction;
  }
  
  public Bindings() {
    this(Bindings::computeDefaultKey);
  }
  
  /**
   * Creates a new instance of Bindings by copying the bindings from another instance.
   *
   * @param other the other Bindings instance to copy from
   */
  public Bindings(Bindings<T> other) {
    this.computeKeyFunction = other.computeKeyFunction;
    this.bindings.putAll(other.bindings);
  }
  
  /**
   * Computes a default key for a symbol based on its full name.<br>
   * <br>
   * <b>NOTE:</b> Sometimes this is not sufficient, e.g. when methods are overloaded with different
   * parameter signatures, they still share the same fully qualified symbol name.
   *
   * @param symbol the symbol for which the key should be computed
   * @return the computed key for the symbol
   */
  public static String computeDefaultKey(ISymbol symbol) {
    return symbol.getFullName();
  }
  
  /**
   * Adds a binding to the set of bindings if there is no conflict with an existing binding.
   *
   * @param binding the binding to add
   * @throws BindingConflictException if there is a conflict with an existing binding.
   */
  public void add(Binding<T> binding) throws BindingConflictException {
    Preconditions.checkNotNull(binding);
    String key = computeKeyFunction.apply(binding.getReferenceElement());
    Binding<T> existingBinding = bindings.get(key);
    if (existingBinding != null) {
      bindings.put(key, existingBinding.mergeOrThrowConflict(binding, computeKeyFunction));
    }
    else {
      bindings.put(key, binding);
    }
  }
  
  /**
   * Checks if the given binding conflicts with an existing binding in this set of bindings.
   *
   * @param binding the binding to check for conflicts
   * @return true if there is a conflict with an existing binding, false otherwise.
   */
  public boolean conflictsWith(Binding<T> binding) {
    return getConflictingBinding(binding).isPresent();
  }
  
  protected Optional<Binding<T>> getConflictingBinding(Binding<T> binding) {
    String key = computeKeyFunction.apply(binding.getReferenceElement());
    return Optional.ofNullable(bindings.get(key)).filter(existingBinding -> existingBinding
        .conflictsWith(binding, computeKeyFunction));
  }
  
  /**
   * Returns the binding for the given reference element if it exists in this set of bindings.
   *
   * @param refElement the reference element for which the binding should be retrieved
   * @return an Optional containing the binding if it exists, or an empty Optional if it does not.
   */
  public Optional<Binding<T>> get(T refElement) {
    Preconditions.checkNotNull(refElement);
    String key = computeKeyFunction.apply(refElement);
    return Optional.ofNullable(bindings.get(key));
  }
  
  /**
   * Returns all bindings in this set of bindings.
   *
   * @return a set of all bindings
   * @implNote The returned set is a copy of the internal map values to ensure immutability.
   */
  public Set<Binding<T>> getAll() { return Set.copyOf(bindings.values()); }
  
}
