/* generated from model null*/
/* generated by template ast.AstClass*/

package de.monticore.umlcd4a.cd4analysis._ast;

import de.monticore.umlcd4a.prettyprint.AstPrinter;

public class ASTCDInterface extends ASTCDInterfaceTOP {
  
  private AstPrinter printer = new AstPrinter();
  
  protected ASTCDInterface() {
  }
  
  protected ASTCDInterface(ASTModifier modifier,
      String name,
      java.util.List<de.monticore.types.types._ast.ASTReferenceType> interfaces,
      java.util.List<de.monticore.umlcd4a.cd4analysis._ast.ASTCDAttribute> cDAttributes,
      java.util.List<de.monticore.umlcd4a.cd4analysis._ast.ASTCDMethod> cDMethods) {
    super(modifier, name, interfaces, cDAttributes,
        cDMethods);
  }
  
  public String printModifier() {
    return super.printModifier();
  }
  
  /**
   * Prints the superclass
   * 
   * @return String representation of the superclass
   */
  public String printInterfaces() {
    return printer.printReferenceList(getInterfaces());
  }
  
}
