package de.monticore.cddiff.syntax2semdiff.SemDiff;

public enum DiffTypes {
  ADDED_ATTRIBUTE,
  REMOVED_ATTRIBUTE,
  ADDED_ASSOCIATION,
  REMOVED_ASSOCIATION,
  CHANGED_ASSOCIATION_MULTIPLICITY,
  CHANGED_ASSOCIATION_DIRECTION,//Do we need to make this even more detailed?
  CHANGED_ASSOCIATION_ROLE,
  ADDED_AGGREGATION,
  REMOVED_AGGREGATION,
  ADDED_OPERATION,
  REMOVED_OPERATION,
  ADDED_INHERITANCE,
  REMOVED_INHERITANCE,
  STEREOTYPE_DIFFERENCE,//Do we need that?
  NAME_DIFFERENCE
}
