/* generated from model null*/
/* generated by template ast.AstClass*/

package de.monticore.umlcd4a._ast;

import de.monticore.types._ast.ASTReferenceTypeList;
import de.monticore.umlcd4a.prettyprint.AstPrinter;

public class ASTCDInterface extends ASTCDInterfaceTOP {
  
  private AstPrinter printer = new AstPrinter();
  
  protected ASTCDInterface() {
  }
  
  protected ASTCDInterface(ASTModifier modifier,
      String name,
      ASTReferenceTypeList interfaces,
      ASTCDAttributeList cDAttributes,
      ASTCDMethodList cDMethods) {
    super(modifier, name, interfaces, cDAttributes,
        cDMethods);
  }
  
  public String printModifier() {
    return super.printModifier();
  }
  
  /**
   * Prints the superclass
   * 
   * @return String representation of the superclass
   */
  public String printInterfaces() {
    return printer.printReferenceList(getInterfaces());
  }
  
}
