<#-- (c) https://github.com/MontiCore/monticore -->
${cdPrinter.printSimpleModifier(ast.getModifier())} ${ast.printType()} ${ast.getName()} ${tc.include("cd2java.Value")};

/**
 * Getter for ${ast.getName()} attribute, generated by overriding a template
 */
public ${ast.printType()} get${ast.getName()?cap_first}() {
  return this.${ast.getName()};
}
