package de.monticore.cd4code._symboltable;

import de.monticore.symbols.basicsymbols._symboltable.TypeSymbol;
import de.se_rwth.commons.logging.Log;

import java.util.List;

public interface ICD4CodeScope extends ICD4CodeScopeTOP{

  @Override
  default public List<TypeSymbol> resolveTypeMany (boolean foundSymbols,String name,
      de.monticore.symboltable.modifiers.AccessModifier modifier,java.util.function.Predicate<de.monticore.symbols.basicsymbols._symboltable.TypeSymbol> predicate) {
    /* generated by template _symboltable.iscope.ResolveMany4IScope*/

    // skip resolution of the symbol, if the symbol has already been resolved in this scope instance
    // during the current execution of the resolution algorithm
    if (isTypeSymbolsAlreadyResolved()) {
      return new de.monticore.symboltable.SetAsListAdapter<>();
    }

    // (1) resolve symbol locally. During this, the 'already resolved' flag is set to true,
    // to prevent resolving cycles caused by cyclic symbol adapters
    //setTypeSymbolsAlreadyResolved(true);
    final List<de.monticore.symbols.basicsymbols._symboltable.TypeSymbol> resolvedSymbols = this.resolveTypeDownMany(foundSymbols, name, modifier, predicate);
    foundSymbols = foundSymbols | resolvedSymbols.size() > 0;
    //setTypeSymbolsAlreadyResolved(false);

    final String resolveCall = "resolveMany(\"" + name + "\", \"" + "TypeSymbol"
        + "\") in scope \"" + (isPresentName() ? getName() : "") + "\"";
    Log.trace("START " + resolveCall + ". Found #" + resolvedSymbols.size() + " (local)", "Resolving");

    // (2) continue with enclosingScope, if either no symbol has been found yet or this scope is non-shadowing
    final List<de.monticore.symbols.basicsymbols._symboltable.TypeSymbol> resolvedFromEnclosing = continueTypeWithEnclosingScope(foundSymbols, name, modifier, predicate);

    // (3) unify results
    resolvedSymbols.addAll(resolvedFromEnclosing);
    Log.trace("END " + resolveCall + ". Found #" + resolvedSymbols.size(), "Resolving");

    return resolvedSymbols;
  }
}
