/* generated from model CD4Code */
/* generated by template core.Class*/

/* (c) https://github.com/MontiCore/monticore */
package de.monticore.cd4code._symboltable.phased;

import de.monticore.cd4code._symboltable.ICD4CodeArtifactScope;
import de.monticore.cd4code._symboltable.ICD4CodeGlobalScope;
import de.monticore.cd4code._visitor.CD4CodeVisitor;
import de.monticore.cdbasis._ast.ASTCDCompilationUnit;

import java.util.ArrayList;
import java.util.List;

abstract public class CD4CodeSymbolTableCreatorDelegatorTOP {
  protected ICD4CodeGlobalScope globalScope;
  protected CD4CodeScopeSkeletonCreatorDelegator scopeSkeletonsCreator;
  protected List<CD4CodeVisitor> priorityList;

  public CD4CodeSymbolTableCreatorDelegatorTOP(ICD4CodeGlobalScope globalScope) {
    this.globalScope = globalScope;
    this.scopeSkeletonsCreator = new CD4CodeScopeSkeletonCreatorDelegator(globalScope);
    this.priorityList = new ArrayList<>();
  }

  /**
   * see {@link de.monticore.cd4code._symboltable.CD4CodeSymbolTableCreatorDelegator#createFromAST}
   *
   * @param rootNode
   * @return
   */
  public ICD4CodeArtifactScope createFromAST(ASTCDCompilationUnit rootNode) {
    ICD4CodeArtifactScope as = scopeSkeletonsCreator.createFromAST(rootNode);
    this.priorityList.forEach(rootNode::accept);
    return as;
  }
}
