/* (c) https://github.com/MontiCore/monticore */
plugins {
  id 'java-library'
  id 'java-gradle-plugin'
  id 'maven-publish'
}


configurations {
  cdTool
}


dependencies {
  implementation "de.se_rwth.commons:se-commons-gradle:$mc_version"
  cdTool "de.monticore.lang:cd4analysis:$mc_version"
  compileOnly(project(":cdlang")) // As the main/cdtool dependency does not have an api dependency to cdlang

  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
  testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_version"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_version"
  testImplementation gradleTestKit()
  testImplementation(project(":cdlang")) // For symbol table tests, etc.
}


sourceSets {
  main.compileClasspath += configurations.cdTool
  test.compileClasspath += configurations.cdTool
}


gradlePlugin {
  plugins {
    cdplugin {
      id = "de.rwth.se.cdgen"
      implementationClass = "de.monticore.cdgen.gradleplugin.CDGenGradlePlugin"
    }
  }
}

publishing {
  repositories.maven {
    credentials.username = mavenUser
    credentials.password = mavenPassword
    def releasesRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/"
    def snapshotsRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/"
    url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
  }
}

// The CDGenGradlePluginTest uses the output of the jar task
test.dependsOn(project(":cdlang").tasks.jar)
test.inputs.files(project(":cdlang").tasks.jar)

// Write the version to the jar
tasks.register('generateResources') {
  ext {
    propFile = file("$buildDir/generated/buildInfo.properties")
  }
  outputs.file propFile
  doLast {
    mkdir propFile.parentFile
    propFile.text = "version=$project.version"
  }
}
processResources {
  from files(generateResources)
  dependsOn generateResources
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
  dependsOn project.tasks.getByPath(":cdlang:jar")
  dependsOn project.tasks.getByPath(":cd-runtime:jar")
  dependsOn generateResources

  // For the MontiVerse
  systemProperty "maven.repo.local", System.getProperty("maven.repo.local")
  systemProperty "useLocalRepo", findProperty("useLocalRepo")
}
