/* (c) https://github.com/MontiCore/monticore */

/* generated from model null*/
/* generated by template ast.AstClass*/

package de.monticore.cd.cd4analysis._ast;

import de.monticore.cd.prettyprint.CD4CodePrinter;

import java.util.Optional;

public class ASTCDInterface extends ASTCDInterfaceTOP {

  private CD4CodePrinter printer = new CD4CodePrinter();

  protected ASTCDInterface() {
  }

  public String printModifier() {
    return super.printModifier();
  }

  /**
   * Prints the superclass
   *
   * @return String representation of the superclass
   */
  public String printInterfaces() {
    return printer.printReferenceList(getInterfaceList());
  }

}
