/* (c) https://github.com/MontiCore/monticore */
/* generated by template symboltable.SymbolReference*/


package de.monticore.cd.cd4analysis._symboltable;

import java.util.ArrayList;
import java.util.List;

import static com.google.common.collect.ImmutableList.copyOf;


/**
 * Represents a loader of {@link CDTypeSymbol}.
 */
public class CDTypeSymbolLoader extends CDTypeSymbolLoaderTOP {

  public CDTypeSymbolLoader(String name, ICD4AnalysisScope enclosingScopeOfReference) {
    super(name, enclosingScopeOfReference);
  }

  private List<CDTypeSymbolLoader> actualTypeArguments = new ArrayList<>();

  private int dimension = 0;

  public List<CDTypeSymbolLoader> getActualTypeArguments() {
    return copyOf(actualTypeArguments);
  }

  public void setActualTypeArguments(List<CDTypeSymbolLoader> actualTypeArguments) {
    this.actualTypeArguments = new ArrayList<>(actualTypeArguments);
  }

  public int getDimension() {
    return dimension;
  }

  public void setDimension(int arrayDimension) {
    this.dimension = arrayDimension;
  }

}

