/* generated from model CDAssociation */
/* generated by template core.Interface*/

/* (c) https://github.com/MontiCore/monticore */
package de.monticore.cdassociation.cocos.ebnf;

import de.monticore.cdassociation._symboltable.SymAssociation;

public interface ICDAssociationSymAssociationCoCo {
  void check(SymAssociation symAssociation);
}
